### ISSUE TITLE
Not compatible with NodeBB v2.1.0

### ISSUE THREAD

**Issue by pooriamehregan** [pitaj/nodebb-plugin-calendar#152] opened 2022-06-07 09:40 UTC
The calendar does not appear after NodeBB upgrade.

![Screenshot from calendar page](https://user-images.githubusercontent.com/50879748/172348835-cb3f0f2e-1124-4af1-b273-f103089a09aa.png)

**Comment by pitaj** [comment] 2022-06-07 13:39
Upgrade from what version? What version of the calendar plugin are you on?

**Comment by pooriamehregan** [comment] 2022-06-08 10:10
I upgraded NodeBB from 1.19.3 to 2.0.1 at first, and then to 2.1.0, and followed the instruction in the [README.md](https://github.com/pitaj/nodebb-plugin-calendar/blob/main/readme.md) file (`npm install nodebb-plugin-calendar@latest`) to upgrade the calendar plugin to make it compatible, but calendar didn't work with either of those versions of NodeBB. I also tried to install the calendar through ACP "Plugins" page. That did't work either.
As a temporary solution I went back to using NodeBB 1.19.3 with `nodebb-plugin-calendar@1.1.3`. With this solution I have turn off the audit check for it to work.

**Comment by pitaj** [comment] 2022-06-08 14:55
And you rebuilt and restarted after installing the new plugin version?

**Comment by pooriamehregan** [comment] 2022-06-09 20:18
Yes, both from the ACP and manually from the terminal.

**Comment by pitaj** [comment] 2022-06-10 02:53
What language do you have set? Are there any errors in the browser console?

**Comment by pitaj** [comment] 2022-06-13 13:34
Looks like your site is having trouble loading the entire script bundle. The error you show isn't caused by the calendar plugin.

Try running `./nodebb build` from the command line. Are there any errors when you do so?

**Comment by pitaj** [comment] 2022-06-14 12:55
Hmm that appeared to work fine. Assuming you still have the issue after a restart:

It's trying to load from localhost:4567. Are you currently running locally? Do you see nodebb.min.js in public/build?

What is your URL in config.json ? Does it match?

**Comment by spongybob2** [comment] 2022-06-22 11:54
I installed this plugin and could not get it work - nodebb v2.2.
The plugin seems to be activated, rebuilt and restarted nodebb, but there's no calendar icon in the composer toolbar - is that where it is supposed to be?
Also when i navigate to /calendar there's only one unstyled button with the text" Show only "Yes" .

**Comment by pitaj** [comment] 2022-06-22 13:41
Are there any errors in the browser console? Please try following the same debug steps above.

**Comment by pitaj** [comment] 2022-06-22 22:38
Please post the full error text including stack trace.

Are there any errors when you build from the command line?

**Comment by spongybob2** [comment] 2022-06-23 06:14
No error from the build.

It's a browser side issue with lots of minified code, eval statements etc... but here's the console's log. Is there a better way to debug this code?
```
localhost/:45          GET http://0.0.0.0:4567/assets/plugins/nodebb-plugin-emoji/emoji/styles.css?v=4h4e0jscv5r net::ERR_FAILED
sockets.js:251 You are accessing the forum from an unknown origin. This will likely result in websockets failing to connect. 
To fix this, set the `"url"` value in `config.json` to the URL at which you access the site. 
For more information, see this FAQ topic: https://community.nodebb.org/topic/13388
eval @ sockets.js:251
eval @ sockets.js:257
./build/public/src/sockets.js @ nodebb.min.js?v=4h4e0jscv5r:389
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ app.js:16
./build/public/src/app.js @ nodebb.min.js?v=4h4e0jscv5r:50
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ client.js:3
./build/public/src/client.js @ nodebb.min.js?v=4h4e0jscv5r:61
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1683
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1685
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/jquery-form/dist/jquery.form.min.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/main.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/matching.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/frequency_lists.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/adjacency_graphs.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/scoring.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/time_estimates.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/zxcvbn/lib/feedback.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/build/public/client.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
scripts-client.js?:formatted:2989 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'template')
    at e (scripts-client.js?:formatted:2989:26)
    at eval (scripts-client.js?:formatted:2997:178)
e @ scripts-client.js?:formatted:2989
eval @ scripts-client.js?:formatted:2997
Promise.then (async)
eval @ scripts-client.js?:formatted:2999
mightThrow @ jquery.js:3766
process @ jquery.js:3834
setTimeout (async)
eval @ jquery.js:3872
fire @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
fire @ jquery.js:3500
fireWith @ jquery.js:3630
ready @ jquery.js:4110
setTimeout (async)
eval @ jquery.js:4131
eval @ jquery.js:28
eval @ jquery.js:40
./node_modules/jquery/dist/jquery.js @ nodebb.min.js?v=4h4e0jscv5r:713
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ app.js:3
./build/public/src/app.js @ nodebb.min.js?v=4h4e0jscv5r:50
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ client.js:3
./build/public/src/client.js @ nodebb.min.js?v=4h4e0jscv5r:61
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1683
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1685
app.js:386 ServiceWorker registration succeeded.
websocket.js:62 WebSocket connection to 'ws://localhost:4567/socket.io/?EIO=4&transport=websocket&sid=By9X_Eal9Y9VS6r4AAAl' failed: 
doOpen @ websocket.js:62
open @ transport.js:57
probe @ socket.js:291
onOpen @ socket.js:313
onHandshake @ socket.js:370
onPacket @ socket.js:332
Emitter.emit @ index.mjs:140
onPacket @ transport.js:114
callback @ polling.js:133
onData @ polling.js:136
Emitter.emit @ index.mjs:140
onLoad @ polling.js:388
xhr.onreadystatechange @ polling.js:323
polling.js:334          POST http://localhost:4567/socket.io/?EIO=4&transport=polling&t=O6FAuDD&sid=By9X_Eal9Y9VS6r4AAAl 400 (Bad Request)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doWrite @ polling.js:236
eval @ polling.js:181
eval @ index.js:19
encodePacket @ encodePacket.browser.js:33
eval @ index.js:16
encodePayload @ index.js:14
write @ polling.js:180
send @ transport.js:81
flush @ socket.js:420
sendPacket @ socket.js:504
write @ socket.js:465
_packet @ manager.js:285
packet @ socket.js:185
onopen @ socket.js:200
Emitter.emit @ index.mjs:140
onopen @ manager.js:206
eval @ manager.js:144
Emitter.emit @ index.mjs:140
onOpen @ socket.js:302
onHandshake @ socket.js:370
onPacket @ socket.js:332
Emitter.emit @ index.mjs:140
onPacket @ transport.js:114
callback @ polling.js:133
onData @ polling.js:136
Emitter.emit @ index.mjs:140
onLoad @ polling.js:388
xhr.onreadystatechange @ polling.js:323
XMLHttpRequest.send (async)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doPoll @ polling.js:252
poll @ polling.js:112
doOpen @ polling.js:66
open @ transport.js:57
open @ socket.js:172
Socket @ socket.js:110
open @ manager.js:137
Manager @ manager.js:66
lookup @ index.js:41
eval @ sockets.js:20
eval @ sockets.js:257
./build/public/src/sockets.js @ nodebb.min.js?v=4h4e0jscv5r:389
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ app.js:16
./build/public/src/app.js @ nodebb.min.js?v=4h4e0jscv5r:50
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ client.js:3
./build/public/src/client.js @ nodebb.min.js?v=4h4e0jscv5r:61
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1683
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1685
polling.js:334          GET http://localhost:4567/socket.io/?EIO=4&transport=polling&t=O6FAuDE&sid=By9X_Eal9Y9VS6r4AAAl 400 (Bad Request)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doPoll @ polling.js:252
poll @ polling.js:112
onData @ polling.js:143
Emitter.emit @ index.mjs:140
onLoad @ polling.js:388
xhr.onreadystatechange @ polling.js:323
XMLHttpRequest.send (async)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doPoll @ polling.js:252
poll @ polling.js:112
doOpen @ polling.js:66
open @ transport.js:57
open @ socket.js:172
Socket @ socket.js:110
open @ manager.js:137
Manager @ manager.js:66
lookup @ index.js:41
eval @ sockets.js:20
eval @ sockets.js:257
./build/public/src/sockets.js @ nodebb.min.js?v=4h4e0jscv5r:389
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ app.js:16
./build/public/src/app.js @ nodebb.min.js?v=4h4e0jscv5r:50
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ client.js:3
./build/public/src/client.js @ nodebb.min.js?v=4h4e0jscv5r:61
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1683
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1685
DevTools failed to load source map: Could not load content for webpack://nodebb/build/public/src/modules/emoji.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://nodebb/node_modules/pulling/build/pulling-drawer.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
hooks.js:34 [hooks] Changes to hooks on this page …
polling.js:334          POST http://localhost:4567/socket.io/?EIO=4&transport=polling&t=O6FAvRr&sid=By9X_Eal9Y9VS6r4AAAl 400 (Bad Request)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doWrite @ polling.js:236
eval @ polling.js:181
eval @ index.js:19
encodePacket @ encodePacket.browser.js:33
eval @ index.js:16
encodePayload @ index.js:14
write @ polling.js:180
close @ polling.js:158
doClose @ polling.js:162
close @ transport.js:68
onClose @ socket.js:574
onError @ socket.js:557
Emitter.emit @ index.mjs:140
onError @ transport.js:46
eval @ polling.js:242
Emitter.emit @ index.mjs:140
onError @ polling.js:356
eval @ polling.js:329
setTimeout (async)
xhr.onreadystatechange @ polling.js:328
XMLHttpRequest.send (async)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doWrite @ polling.js:236
eval @ polling.js:181
eval @ index.js:19
encodePacket @ encodePacket.browser.js:33
eval @ index.js:16
encodePayload @ index.js:14
write @ polling.js:180
send @ transport.js:81
flush @ socket.js:420
sendPacket @ socket.js:504
write @ socket.js:465
_packet @ manager.js:285
packet @ socket.js:185
onopen @ socket.js:200
Emitter.emit @ index.mjs:140
onopen @ manager.js:206
eval @ manager.js:144
Emitter.emit @ index.mjs:140
onOpen @ socket.js:302
onHandshake @ socket.js:370
onPacket @ socket.js:332
Emitter.emit @ index.mjs:140
onPacket @ transport.js:114
callback @ polling.js:133
onData @ polling.js:136
Emitter.emit @ index.mjs:140
onLoad @ polling.js:388
xhr.onreadystatechange @ polling.js:323
XMLHttpRequest.send (async)
create @ polling.js:334
Request @ polling.js:276
request @ polling.js:226
doPoll @ polling.js:252
poll @ polling.js:112
doOpen @ polling.js:66
open @ transport.js:57
open @ socket.js:172
Socket @ socket.js:110
open @ manager.js:137
Manager @ manager.js:66
lookup @ index.js:41
eval @ sockets.js:20
eval @ sockets.js:257
./build/public/src/sockets.js @ nodebb.min.js?v=4h4e0jscv5r:389
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ app.js:16
./build/public/src/app.js @ nodebb.min.js?v=4h4e0jscv5r:50
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
eval @ client.js:3
./build/public/src/client.js @ nodebb.min.js?v=4h4e0jscv5r:61
__webpack_require__ @ nodebb.min.js?v=4h4e0jscv5r:1404
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1683
(anonymous) @ nodebb.min.js?v=4h4e0jscv5r:1685
manifest.webmanifest:1 Manifest: property 'start_url' ignored, should be same origin as document.
hooks.js:28 [hooks] Registered filter:notifications.load ({ notifications: notifs }) => new Promise((resolve) => {
		translator.toggleTimeagoShorthand(function () {
			for (let i = 0; i < notifs.length; i += 1) {
				notifs[i].timeago = $.timeago(new Date(…
```

**Comment by pitaj** [comment] 2022-06-23 14:02
Have you tried disabling all other plugins? Try the persona theme if you aren't already using it.

**Comment by spongybob2** [comment] 2022-06-24 04:15
It's just this plugin (beside the default ones) and the persona theme

**Comment by spongybob2** [comment] 2022-07-01 19:34
It seems it has to do with the availability of `ajaxify.data` before is it populated with `ajaxify.parseData()`
It all lies in `client/index.ts`. A quick fix would be:
```
diff --git a/src/client/index.ts b/src/client/index.ts
index 9be53d9..de4e19b 100644
--- a/src/client/index.ts
+++ b/src/client/index.ts
@@ -6,7 +6,7 @@ __webpack_public_path__ = `${config.relative_path}/assets/plugins/nodebb-plugin-
 jQuery.fn.size = jQuery.fn.size || function size(this: JQuery) { return this.length; };
 
 const calendarLoad = () => {
-  if (ajaxify.data.template.calendar) {
+  if (ajaxify.temple && ajaxify.data.template.calendar) {
     import('../calendar');
 
     $('#plugin-calendar-cal-event-display').modal({
```

**Comment by pitaj** [comment] 2022-07-01 19:55
Yes I'm aware of the problem and I'm trying to get core devs to fix it on their end.

**Comment by pitaj** [comment] 2022-07-05 01:25
Fixed by https://github.com/NodeBB/NodeBB/commit/b778e38c2b94772e5ac7b06db7c2f5dba098e284
A NodeBB patch version will be issued soon

**Closed by pitaj** 2022-07-05 01:25 UTC
