### ISSUE TITLE
Week start for calendar

### ISSUE THREAD

**Issue by craigco** [pitaj/nodebb-plugin-calendar#66] opened 2016-12-10 21:57 UTC
Is it possible to change the calendar week start day?  Mine is defaulting to Monday and I would like to change it to Sunday.

Is this a system setting?

**Comment by pitaj** [comment] 2016-12-10 21:59
It's based on whatever language you have selected in NodeBB. Try using `en-US` instead of `en-GB`, assuming you're already on that.

**Comment by craigco** [comment] 2016-12-10 22:04
lol!   Thank you.

**Comment by sharked76** [comment] 2019-03-27 13:49
I am having the same issue, some of my users want the week to start on Sunday not Monday, I have tried changing the Language from en-GB to en-US and vice-versa and there is no change to the week start in the calendar?  Is this setting now moved somewhere else?

**Comment by pitaj** [comment] 2019-03-27 14:46
The setting has not moved. Where are you changing the language? You should be changing it in your user settings.

**Comment by sharked76** [comment] 2019-03-27 16:42
I was clicking on my Avator, clicking Settings and then in the top right change the language from en-GB to en-US, then I click save.  I think logged out and then logged in again and there is no change to the calendar.  I even tried different browser and computer.  From what I can see changing from en-GB to en-US does not make any change at all to the start week of the calendar, its always starting on Monday.

**Comment by sharked76** [comment] 2019-04-02 15:06
Hi, just wondering if you have any update on this?  Is there a setting in the ACP somewhere where I can force the week to start on Sunday for everyone?  

My old forum calendar had the week start on Sunday so that is what they are used to.

**Comment by pitaj** [comment] 2019-04-02 17:54
I have yet to look into this. I'm sorry it's taking me so long but I've been very busy.

I'll reopen the issue, though.

**Comment by sharked76** [comment] 2019-04-19 14:28
Hi just wondering about this, any update on how to set the start of the week to Sunday instead of Monday?  Is there a config file somewhere I can just edit to make the week start on Sunday?

**Comment by pitaj** [comment] 2019-04-19 15:26
I don't know what to tell you, I haven't had a chance to look into this, and last I checked you should just need to set `en-US` as your language.

**Comment by sharked76** [comment] 2019-04-19 19:00
Yeah, I changed that and it didn't change anything.  Can you make it so there is a config .conf file and we just edit? that would be easier and is most common way of doing settings in Linux?

**Comment by pitaj** [comment] 2019-04-19 20:52
The layout of the calendar is set client-side.

**Comment by sharked76** [comment] 2019-04-19 23:34
Can it be changed so its server wide setting not client setting?  Even if the client setting worked, (which it doesn't) then I would have to edit every single user account to make the change.

**Comment by pitaj** [comment] 2019-04-20 02:26
It might be possible to override the client side setting with some custom JavaScript code, but I'll have to take a look this coming week.

**Comment by sharked76** [comment] 2019-04-20 19:44
Ok thanks, so when I change the country to English/United States and then look at the calendar it just shows blank:

![image](https://user-images.githubusercontent.com/48071101/56461547-de6b8f00-6382-11e9-83e5-f48f0ed2d3a1.png)


If I change the country back to English/United Kingdom/Canada then the calendar is restored, but the start of the week is Monday.

![image](https://user-images.githubusercontent.com/48071101/56461574-2db1bf80-6383-11e9-907b-10a39919e999.png)


I have many users asking me how to change the calendar to look like a normal calendar with Sunday as the 1st of the week, I don't know any calendar that starts on Monday, so not sure why it would default to this layout.

**Comment by pitaj** [comment] 2019-04-26 04:04
Fixed in nodebb-plugin-calendar@1.0.0-alpha.48

**Closed** 2019-04-26 04:04 UTC
Labels: question, solved

**Comment by sharked76** [comment] 2019-04-26 14:26
Thank you!!!

Duane

________________________________

**Comment by sharked76** [comment] 2019-04-28 00:37
Hi, I am not sure how to fix this, but since updating to the new version and changing to US-En, now I notice that some calendar entries are showing like this:

[cid:ab924096-77a3-4935-893a-0f174123b07f]

Any ideas?

Duane



________________________________

**Comment by pitaj** [comment] 2019-04-28 00:52
Your image isn't showing up because you submitted it with email.

**Comment by sharked76** [comment] 2019-04-28 02:03
![image](https://user-images.githubusercontent.com/48071101/56857157-3f253980-6938-11e9-9f16-fe83d2096179.png)

**Comment by pitaj** [comment] 2019-04-28 02:13
I'm not able to reproduce this. Can you see if there are any errors in the javascript console in your browser, and provide the exact post content you're using? Thanks

**Comment by sharked76** [comment] 2019-04-28 02:28
![image](https://user-images.githubusercontent.com/48071101/56857354-70066e00-693a-11e9-93ae-77a5877fff4e.png)

Weird thing is when I click on Edit in that Post, there is no calendar icon to click on?

![image](https://user-images.githubusercontent.com/48071101/56857446-ac869980-693b-11e9-85cb-671bd467de7b.png)

I am logged in as Admin, and Admin has full access to this forum:

![image](https://user-images.githubusercontent.com/48071101/56857450-cb852b80-693b-11e9-942b-957acb46dedd.png)

**Comment by sharked76** [comment] 2019-04-28 02:29
`[event][name]Club Night Avail CSSA Instructors[/name][allday]false[/allday][startDate]1557181800000[/startDate][endDate]1557189000000[/endDate][reminders][][/reminders][location]Indoor Range and Selected Outdoor Ranges[/location][description]Instructors on Duty 
Andrea Palmigiani
Marcell Wolf
Adam Smith[/description][mandatory]false[/mandatory][/event]`

**Comment by sharked76** [comment] 2019-04-28 02:35
It seems to be the same for all calendar entries:

![image](https://user-images.githubusercontent.com/48071101/56857480-2880e180-693c-11e9-8077-98e880f960d0.png)

And the same issue even if I login as a normal user without Admin access:

![image](https://user-images.githubusercontent.com/48071101/56857498-5c5c0700-693c-11e9-9ce0-aea6743f2e6f.png)



Could it be because all these calendar events were created prior to me changing the language from English/United Kindom/Canada to English/USA ?


Same thing happens in Calendar View when I click on a Event:

![image](https://user-images.githubusercontent.com/48071101/56857541-ce345080-693c-11e9-826c-a6193f3c0a8d.png)

**Comment by pitaj** [comment] 2019-04-28 02:41
I'm not able to reproduce this on any browser. Can you try running `./nodebb stop && ./nodebb build && ./nodebb start` and trying again?

Also, can you provide the output of the following:

- `node -v`
- `./nodebb -V`
- `npm ls nodebb-plugin-calendar`

**Comment by pitaj** [comment] 2019-04-28 02:42
Also the forum default language and the language setting for each user would be good info to have.

**Comment by sharked76** [comment] 2019-05-13 17:43
Sorry I was out of town for the past couple weeks.  I keep having this same issue, and I have some users reporting it also.  For example 1 user when he looks on his Samsung Phone, he has the giberish, but when he looks at the same calendar on Amazon Fire Tablet its normal.

`bgc@server1:~$ node -v
v10.15.3

bgc@server1:~/nodebb$ ./nodebb -V
1.12.1

bgc@server1:~/nodebb$ npm ls nodebb-plugin-calendar
nodebb@1.12.1 /home/bgc/nodebb
└── nodebb-plugin-calendar@1.0.0-alpha.48



`



Default Forum Language:
English (United States) (en-US)

Language Setting for User:
English (United States) (en-US)


I also noticed for example, if I login to the forum with my user on normal chrome browser and I view the calendar I see the giberish, but then I use the same user but switch Incognito browser the calendar displays normally?

Could this issue be related to Ngix reverse proxy on the server? or some kind of browser cache issue?

It just seems odd that it only started happening after you fixed the issue with setting the user langugue for the week start in the calendar.

Duane

**Comment by pitaj** [comment] 2019-05-13 17:49
It sounds like a browser cache issue for sure

**Comment by sharked76** [comment] 2019-05-13 18:00
Any ideas what could be causing it? Its multiple users on different devices?  There were no reports of this prior to me updating to 1.0.0-alpha.48  Is there some kind of detailed logging I can enable?  I also have another users who does not see anything, just blank calendar with only this showing:  

![IMG_0658](https://user-images.githubusercontent.com/48071101/57643308-6f4f1800-7587-11e9-918d-4ef9afa2e43b.PNG)

**Comment by pitaj** [comment] 2019-05-13 19:52
It's probably because I changed some things, so new bundles were generated but under the same names as before, so they're kept cached. I suggest you recommend your users to clear their caches. I'll see what I can do to set up a cache-defeat mechanism to prevent this in the future.

**Comment by pitaj** [comment] 2019-05-13 19:54
#118
