### ISSUE TITLE
Calendar v0.7 Alpha broken on NodeBB 1.2.1

### ISSUE THREAD

**Issue by gnucoder** [pitaj/nodebb-plugin-calendar#63] opened 2016-10-24 09:11 UTC
Calendar v0.7 Alpha on NodeBB to 1.2.1 (maybe 0.8 Alpha as well) 

- The list of attendees doesn’t display anymore when we click on a "Yes" "Maybe" "No".
- It's just like the JS action on the button is not working... When we clic nothing is happening.
- The calendar button in the markdown composer is inactif, nothing is happening when clicking.

Tks :)

**Comment by pitaj** [comment] 2016-10-24 23:42
Duplicate of #58

**Closed by pitaj** 2016-10-24 23:42 UTC
